### ISSUE TITLE
Can not start timemachine from docker compose

### ISSUE THREAD

**Issue by longwdl** [odarriba/docker-timemachine#7]
Container will exit after start.

```
> docker-compose up
Creating ittimemachine_tm_1
Attaching to ittimemachine_tm_1
tm_1 | Starting Netatalk services:  netatalk.
ittimemachine_tm_1 exited with code 0
```

my docker-compose file:

```
tm:
  image: odarriba/timemachine
  hostname: tm.xxx.com
  volumes:
    - /mnt/hdd/data/timemachine:/timemachine
  ports:
    - '548:548'
    - '636:636'
  environment:
    AFP_LOGIN: usr
    AFP_PASSWORD: pwd
    AFP_NAME: Time_Machine
    AFP_SIZE_LIMIT: 2000000
```
